Chris:  # Riders Name
  # R03:                                   # no lap number!!
  #   Desc: 'Baseline'
  #   ValidLaps: [3,4,5,6,7,8,9,10,11]
  R04:  
    Desc: 'Baseline 2'
    ValidLaps: [3,4,5,6,7]  # weight readings not correct on lap 8
  R05:  
    Desc: 'Rod'
    ValidLaps: [3,4,5,6,7,8,9,10]
  R06:  
    Desc: '50mm Disc'
    ValidLaps: [3,4,5,6,7,8]
  R07:  
    Desc: '60mm Disc'
    ValidLaps: [3,4,5,6,7,8]
  R08:  
    Desc: '80mm Disc'
    ValidLaps: [3,4,5,6,7,8]



